export const READ_USERS = "READ_USERS";
export const READ_QUESTIONS = "READ_QUESTIONS";
export const SET_AUTH_USER ="SET_AUTH_USER";
export const LOG_OUT = "LOG_OUT";
export const ADD_QUESTION ="ADD_QUESTION";
export const ADD_QUESTION_TO_USER ="ADD_QUESTION_TO_USER";
export const ADD_ANSWER_TO_USER = "ADD_ANSWER_TO_USER";
export const ADD_ANSWER = "ADD_ANSWER";
export const UPDATE_AUTH_USER = "UPDATE_AUTH_USER";

